### ISSUE TITLE
pretty-print `AntiTypeDecl`

### ISSUE THREAD

**Issue by zilinc** [mainland/language-c-quote#44]
If I parse a piece of C code consisting of `$ty:(something)`, then there're chances that the AST has `AntiTypeDecl "something" loc` in it. But I don't see a way to `ppr` it. It leads to non-termination because the only base case in the recursive `pprDecl` function is `DeclRoot loc'. Though I'm not clear what's the rationale behind it, printing out the antiquotation as-is seems to be a natural treatment. If there are reasons indeed, it'd be better documented, and provide another function that does it. Please correct me if I'm mistaken. Thanks.

**Comment by mainland** [comment]
Pull request welcome!
