### ISSUE TITLE
Objective-C anti-quotations for interface decls broken

### ISSUE THREAD

**Issue by mchakravarty** [mainland/language-c-quote#51]
I know, I'm late to the party, but I just noticed that the changes between version 0.9 and 0.10.0 made to Objective-C anti-quotations are broken. Specifically, `language-c-inline` has got a binding like this
```
iface = [cunit| 
  @interface $id:prefixedClassName : NSObject
            
  $ifdecls:propertyDecls
  $ifdecls:updateMethodDecls
  $ifdecls:ifaceDecls
            
  @end
|]
```
Unfortunately, this pretty prints without expanding the anti-quotations; so, I get
```
@interface Particle : NSObject 
$ifdecls:propertyDecls
$ifdecls:updateMethodDecls
$ifdecls:ifaceDecls
@end
```
From what I can see, it must have been the changes between https://github.com/mainland/language-c-quote/commit/1627e2518928cdeeb874cf5a52f631603661aa77 and https://github.com/mainland/language-c-quote/commit/fa982197eb31edcb7f9d72910965c92b807a6df5 (which clang really doesn't like).

**Comment by mainland** [comment]
Do you have a complete example that we could add to the test suite?
