### ISSUE TITLE
Support for lambda-expressions

### ISSUE THREAD

**Issue by mwu-tow** [mainland/language-c-quote#52]
Hi,
would it be possible to add support for lambda-expressions from C++11? It is needed for the `accelerate-cuda` package in order to work on Windows (AccelerateHS/accelerate#234) or take advatange of the new runtime compilation library (AccelerateHS/accelerate#258).
Currently `accelerate-cuda` uses expression statements that are non-portable GNU extension. It can be and needs to be replaced with lambda-expressions. I did a quick hack (mwu-tow/language-c-quote@e670cfd) to pretty printer, so the expression statements are translated to lambda-expressions — and it was confirmed to solve the issues. 

Ideally, the lambda-expressions support should be added to `language-c-quote` — that includes defining new AST structures, parsing and code pretty printing. 
However, I'm not sure how it fits in. Lambdas are C++ feature, they are not part of C language. Should they only work in CUDA extensions mode? Is this an acceptable extension fitting the purpose of this package?

Please, let me know what is your view on this issue and how we should proceed from here.

**Comment by mainland** [comment]
It sounds like the proper place to put this would be the CUDA quasiquoter. I would accept a patch (with docs, unit tests, etc.)

**Comment by mwu-tow** [comment]
Thank you for the answer. I am working on implementing this. Soon I'll submit PR with my first take on this feature. As I have no prior experience on working with happy (or any larger Haskell project), I'll likely need your guidance to get this right. I hope it is acceptable. :)

**Comment by mwu-tow** [comment]
@mainland 
Could you provide any ETA when you will be able to check the #53 or to suggest an alternative solution for this issue? It is a blocker for running `accelerate-cuda` on Windows — a thing that I'm vitally interested in. 
I understand that you might be really busy now but it'd nice if I at least knew that you saw the PR and are going to answer.

**Comment by mainland** [comment]
Yes, I see the issue. The term just started, and I do not have an ETA for you, sorry.

**Comment by mainland** [comment]
Merged, thanks!
