### ISSUE TITLE
No obvious way to generate macro code -- not even through $esc:(... :: String)

### ISSUE THREAD

**Issue by deepfire** [mainland/language-c-quote#59]
It doesn't seem possible at all to generate C code referring to macro calls.

Not even through the supposedly almighty dirty escape hatch:
```
[citems|
struct cap *cap;
$esc:("list_for_each (cap, list, &acl->list)")
        printf ("cap: %s\n", cap->name);
|]
```
yields:
```
parse error on `$esc:("list_for_each (cap, list, &acl->list)")'
```

**Comment by mainland** [comment]
Yes, `$esc` is only valid for external declarations.

`language-c-quote` is a C parser, not a C + CPP parser :) Parsing the latter is much more difficult.

**Comment by deepfire** [comment]
..but why not add a *really* dirty escape hatch, then -- one that would pass through *any* string as-is, unsafePerformIO-style?

**Comment by mainland** [comment]
1) Nobody asked for it , 2) I didn't need it, 3) because then the AST would need to be modified everywhere one might want to insert a raw string, leading to a large number of new data constructors.

**Comment by deepfire** [comment]
I think the vast majority of real-world cases could be covered with just two AST points -- expressions and declarations.

**Comment by deepfire** [comment]
Trying to implement this..

**Comment by mainland** [comment]
Now that #60 has been merged, I believe this issue has been resolved.
