### ISSUE TITLE
Wrong declaration AST coming out of quotation?

### ISSUE THREAD

**Issue by deepfire** [mainland/language-c-quote#62]
The information about the return type of functions in arrays seems to be spread out into very distant parts of AST -- so much so it appears.. not really rationalizable for a bystander armed with a general knowledge of C.

This can be illustrated with two cases -- functions returning "void" and "void *" -- note how the "void" piece is part of the outer `DeclSpec` and the "pointer to" piece is buried within `Array->Ptr->OldProto`:

(*Note: the outer DecDef has been dropped for posterity.  The examples were obtained using GHCi with `language-c-quote` version `0.11.4`*)

`[cedecl|void *(*foo[2])();|]`
```
InitGroup (DeclSpec [] [] (Tvoid noLoc) noLoc)
          []
          [Init (Id "foo" noLoc)
                (Array []
                       (ArraySize False (Const (IntConst "2" Signed 2 noLoc) noLoc) noLoc)
                       (Ptr [] (OldProto (Ptr [] (DeclRoot noLoc) noLoc) [] noLoc) noLoc)
                       noLoc)
                Nothing Nothing [] noLoc] noLoc
```

`[cedecl|void (*foo[2])();|]`
```
InitGroup (DeclSpec [] [] (Tvoid noLoc) noLoc)
          []
          [Init (Id "foo" noLoc)
                (Array []
                       (ArraySize False (Const (IntConst "2" Signed 2 noLoc) noLoc) noLoc)
                       (Ptr [] (OldProto (DeclRoot noLoc) [] noLoc) noLoc)
                       noLoc)
                Nothing Nothing [] noLoc] noLoc) noLoc
```

**Comment by mainland** [comment]
```
Type `help' or `?' for help
cdecl> explain void *(*foo[2])()
declare foo as array 2 of pointer to function returning pointer to void
cdecl> explain void (*foo[2])()
declare foo as array 2 of pointer to function returning void
cdecl>
```

The AST looks correct to me. What do you think it should be?

**Comment by deepfire** [comment]
Geoffrey, I am sorry for making the noise.

The AST does indeed correctly follow the C language quirks, where one can say
```
char foo = 'a', *bar = "b";
```
..which necessitates the split of the type and pointer information into two different places within the AST.

One can be found as regretful of this complication, even if it is understandable..

Once again, sorry for the noise!
