### ISSUE TITLE
Add to Stackage

### ISSUE THREAD

**Issue by Athas** [mainland/language-c-quote#67]
The `language-c-quote` package seems to exist in an old-ish LTS and a nightly snapshot from December:

https://www.stackage.org/package/language-c-quote

Since this package is a really wonderful way to generate C ASTs, it would be nice if it was included in new nightly and LTS snapshots.  Was there a reason it was removed?  I don't much know how Stackage is managed.

**Comment by mainland** [comment]
I don't know why it was removed---you would have to ask the stack folks :) I also do not know much about how Stack is managed.

**Comment by Athas** [comment]
I suspect it was due to the Alex-related breakage a few months ago (at least language-c-quote doesn't build in the December snapshot).

**Comment by Athas** [comment]
I think I figured it out - it was a temporary block that nobody got around to removing again.  I have made a pull request that removes it: https://github.com/fpco/stackage/pull/1359

**Comment by Athas** [comment]
Looks like language-c-quote is getting picked up by nightly Stackage builds again: https://www.stackage.org/nightly-2016-04-13

I guess it will also eventually make it into LTS releases, so closing this.

**Comment by mainland** [comment]
Thanks!
