### ISSUE TITLE
The antiquoter for double and float does not handle infinity correctly

### ISSUE THREAD

**Issue by Athas** [mainland/language-c-quote#69]
If you antiquote a positive infinite value, you will get the expression `Infinity` (I think it just calls show on the float).  There may not be a sensible thing to do here (you can always just define a constant `Infinity` yourself).  C99 does define `INFINITY` in `math.h`, which may be slightly better than the current behaviour.

It is likely that a similar issue exists for NaNs.

**Comment by mainland** [comment]
Floating point numbers are represented as `Rational`s in the AST, which is the root of the problem. I'm not sure what the best solution is either; using a `#define`'d value seems like the best option off-hand.

**Comment by mainland** [comment]
This should be fixed now. NaN's are printed as `NAN`, and infinity as `INFINITY`.
