### ISSUE TITLE
No nested quotations examples

### ISSUE THREAD

**Issue by grwlf** [mainland/language-c-quote#77]
I badly want nested quotations, but still I have no luck using `\|\]` from the README. Could you please clarify the status of this feature?

**Comment by mainland** [comment]
Try `\\|\\]`. If that doesn't work, please submit a minimal non-working example that I can easily test myself.

**Comment by grwlf** [comment]
`\\|\\]` doesn't help in my case

**Comment by mainland** [comment]
`haskell-src-meta` does not support parsing quasiquotations, so nested quotations do not work.
