### ISSUE TITLE
Missing braces cause dangling-else

### ISSUE THREAD

**Issue by michalpalka** [mainland/language-c-quote#81]
Consider the following module:
```haskell
{-# LANGUAGE QuasiQuotes #-}
module DanglingElse where

import Language.C.Quote.C
import Text.PrettyPrint.Mainland
import Text.PrettyPrint.Mainland.Class

import System.IO

mainProg = [cunit|
  $esc:("#include <stdio.h>")

  int main() {
    int x = 1;
    if (x > 1) {
      // This comment is needed to trigger the dangling-else problem
      if (x > 2) {
        printf("a\n");
      }
    } else {
      printf("b\n");
    }
  }|]

main = do
  withFile "dangling.c" WriteMode $ \h -> do
    hPutDocLn h $ ppr mainProg
```

Running `main` will create `dangling.c` with the following contents:

```c
#include <stdio.h>
int main()
{
    int x = 1;

    if (x > 1)
        // This comment is needed to trigger the dangling-else problem
        if (x > 2)
            printf("a\n");
    else
        printf("b\n");
}
```

As you can see, the braces around the body of the outer `if` are missing. As a result, we have a _dangling-else clause_, which can be attributed to any of the `if`s. Compiling the file with clang 4.0.1 yields the following warning:

```
$ clang -o dangling dangling.c
dangling.c:10:5: warning: add explicit braces to avoid dangling else [-Wdangling-else]
    else
    ^
1 warning generated.
```

Running the resulting executable produces no output, from which we conclude that the `else` clause is interpreted as belonging to the inner `if`, contrary to our intention. We believe that it is a bug.

Interestingly, the problem goes away when we remove the C comment line from the quoted C fragment, which results in the braces being present.

As a workaround, we may insert a dummy statement (a `;`) before the comment line, which also makes the problem go away.

**Comment by athas** [comment]
I can reproduce.  Very unfortunate.  Will see if I can figure out a fix.

**Comment by athas** [comment]
The problem is that the pretty printing definition for `If` has a special case for detecting nested `If`s, but I guess a preceding comment looks different.  I can probably fix this.  (Although for simplicity, I'd probably prefer to just always put braces on everything.)
