### ISSUE TITLE
support GHC 9.10

### ISSUE THREAD

**Issue by ulysses4ever** [mainland/language-c-quote#95]

**Comment by athas** [comment]
I have bumped the bound and issued a revision on Hackage.

**Comment by ulysses4ever** [comment]
Thank you!

**Comment by athas** [comment]
How so? Doesn't GHC 9.10 come with bytestring-0.12.1.0? The language-c-quote bound is <0.13.

**Comment by ulysses4ever** [comment]
Sorry, it's filepath<1.5 that hits me. (One day I will learn how to read cabal solver messages...)

**Comment by ulysses4ever** [comment]
Hey @athas! Sorry that I didn't check it exhaustively beforehand. For `language-quote-c` to be built with GHC 9.10 under Haskell-CI (or, more generally, with `constraints: * installed`), we need a version bump for `filepath`. Would it be possible to do so?

**Comment by ulysses4ever** [comment]
It looks like 0.13.0.2 was uploaded recently, and it solves my issue by bumping the `filepath` bound. Thanks all!
